vino_etu/.gitignore, vino_etu/.project, vino_etu/Controler.class.php, vino_etu/README.md, vino_etu/config.php, vino_etu/css/base_h5bp.css, vino_etu/css/main.css, vino_etu/css/normalize.css, vino_etu/data/vinodb.sql, vino_etu/index.php, vino_etu/indexTest.php, vino_etu/js/main.js, vino_etu/lib/MonSQL.class.php, vino_etu/lib/SAQ.class.php, vino_etu/lib/Utilitaires.class.php, vino_etu/modeles/Bouteille.class.php, vino_etu/modeles/Modele.class.php, vino_etu/test/gabarit.test.php, vino_etu/test/index.php, vino_etu/updateSAQ.php, vino_etu/var.init.php, vino_etu/vues/ajouter.php, vino_etu/vues/cellier.php, vino_etu/vues/entete.php, vino_etu/vues/pied.php
Beaucoup de commit inutile, car beaucoup de difficulté à le mettre en place
=> Ajout du dossier vino_etu dans le projet de base 

charteGraphique.pdf
Création de la charte graphique Issue #38
=> Ajout de la charte graphique #38

vino_etu/Controler.class.php, vino_etu/lib/SAQ.class.php, vino_etu/modeles/Bouteille.class.php, vino_etu/vues/cellier.php, vino_etu/vues/modifier.php
pour modification le bottel en cellier :
1. créer une page modificatrice
2. créer le contrôleur et la fonction dans le modèle
3.changer la page cellier pour accéder à la page modificateur 
#3
=> créer  page modification  

vino_etu/Controler.class.php, vino_etu/js/main.js, vino_etu/lib/SAQ.class.php, vino_etu/modeles/Bouteille.class.php, vino_etu/vues/ajouter.php, vino_etu/vues/cellier.php, vino_etu/vues/modifier.php
=> Commenter le code source

vino_etu/lib/SAQ.class.php
=> formatage du prix à enregistrer dans la base de données

vino_etu/lib/SAQ.class.php, vino_etu/modeles/Bouteille.class.php
changement modifier la fonction getListeBouteilleCellier  pour afficher des images.
#33
=> changement modifier la fonction getListeBouteilleCellier 

vino_etu/indexTest.php, vino_etu/test/index.php
=> modification fichier test-unitaire

ListeOperations.md
=> Ajout du fichier Liste des opérations modèle avec l'ajout des attributs 

API-vino/react/src/main.jsx
=> undo fichier main.jsx

API-vino/package-lock.json, API-vino/react/index.html, API-vino/react/src/App.jsx, API-vino/react/src/main.jsx
=> modifier la configuration de react

API-vino/.editorconfig, API-vino/react/src/App.jsx, API-vino/react/src/Router.jsx, API-vino/react/src/main.jsx, API-vino/react/src/vues/Inscription.jsx, API-vino/react/src/vues/Login.jsx, API-vino/react/src/vues/Usager.jsx
créer des routeurs et composants Login, Inscription et Usager
#35
=> créer des routeurs

API-vino/app/Models/ListeCellier.php, API-vino/app/Providers/AppServiceProvider.php, API-vino/react/src/ListeCellier/ListeCellier.jsx, API-vino/react/src/composants/Entete/Entete.jsx, API-vino/react/src/vues/Cellier/Cellier.jsx, API-vino/routes/api.php
=> créer une api pour afficher la liste des bouteilles en cellier

API-vino/react/src/ListeCellier/ListeCellier.jsx
=> modifier le composant listeCellier

API-vino/app/Models/Bouteille.php, API-vino/react/src/composants/Entete/Entete.jsx, API-vino/routes/api.php
#82 
modifie api pour update bouteille et supprimer
=> modifie api pour update bouteille

API-vino/package-lock.json, API-vino/package.json, API-vino/react/src/composants/Bouteille/Bouteille.jsx, API-vino/react/src/vues/ListeBouteille/ListeBouteille.css, API-vino/react/src/vues/ListeBouteille/ListeBouteille.jsx
=> trier des bouteilles par nom et prix

API-vino/react/src/composants/Bouteille/Bouteille.jsx, API-vino/react/src/vues/ListeBouteille/ListeBouteille.css, API-vino/react/src/vues/ListeBouteille/ListeBouteille.jsx, API-vino/routes/api.php
=> ajoute recherche dans le cellier

API-vino/database/migrations/2023_05_25_185610_create_vino_usager_table.php, API-vino/react/src/Router.jsx, API-vino/react/src/composants/Entete/Entete.jsx, API-vino/react/src/vues/Inscription/Inscription.jsx, API-vino/react/src/vues/Login/Login.jsx, API-vino/routes/api.php
=> modifier la fonction d'enregistrement

API-vino/app/Http/Controllers/CellierController.php, API-vino/react/src/App.jsx, API-vino/react/src/assets/css/general.css, API-vino/react/src/composants/Bouteille/Bouteille.jsx, API-vino/react/src/composants/Cellier/Cellier.css, API-vino/react/src/composants/Entete/Entete.css, API-vino/react/src/composants/Entete/Entete.jsx, API-vino/react/src/composants/Pied/Pied.jsx, API-vino/react/src/global/authentification/authAction.jsx, API-vino/react/src/global/authentification/authReducer.jsx, API-vino/react/src/main.jsx, API-vino/react/src/vues/Accueil/Accueil.css, API-vino/react/src/vues/Accueil/Accueil.jsx, API-vino/react/src/vues/Formulaire/AjoutBouteille.jsx, API-vino/react/src/vues/ListeBouteille/ListeBouteille.css, API-vino/react/src/vues/ListeBouteille/ListeBouteille.jsx, API-vino/react/src/vues/ListeCellier/ListeCellier.css, API-vino/react/src/vues/ListeCellier/ListeCellier.jsx, API-vino/react/src/vues/Login/Login.jsx, API-vino/routes/api.php
pour acceder a la ListeCellier et ListeBouteille, Modification de ListeCellier pour ajouter juste les cellier de l'usager, Correction du bug suppression de bouteille dans listeBouteille
Issue #134
=> Authentification obligatoire partie 2

API-vino/react/src/App.jsx, API-vino/react/src/assets/css/general.css, API-vino/react/src/composants/Entete/Entete.jsx, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/ListeBouteille/ListeBouteille.css, API-vino/react/src/vues/ListeBouteille/ListeBouteille.jsx, API-vino/react/src/vues/Login/Login.jsx
Creation de l'espace admin avec une redirection à la connection 
Et une navigation différente si admin
issue #140
=> Creation de l'espace Admin

API-vino/app/Http/Controllers/AuthController.php, API-vino/composer.lock, API-vino/react/package-lock.json, API-vino/react/src/composants/Validation/ValidationInscription.jsx, API-vino/react/src/composants/Validation/ValidationLogin.jsx, API-vino/react/src/vues/Inscription/Inscription.jsx, API-vino/react/src/vues/Login/Login.jsx
=> validation formulaire de validation enregistrement

API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx
=> liste des utilisateurs et suppression d'un utilisateur

API-vino/.htaccess, API-vino/app/Http/Controllers/BouteilleController.php, API-vino/app/Http/Controllers/SAQController.php, API-vino/app/Http/Kernel.php, API-vino/composer.json, API-vino/composer.lock, API-vino/config/app.php, API-vino/config/cors.php, API-vino/react/src/composants/ImportationSAQ/ImportationSAQ.jsx, API-vino/react/src/styles.css, API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/Inscription/Inscription.jsx, API-vino/react/src/vues/Login/Login.jsx, API-vino/routes/api.php
=> Insertion des bouteilles de la SAQ

API-vino/app/Http/Controllers/CellierBouteillesController.php, API-vino/react/src/assets/css/modales.css, API-vino/react/src/composants/Validation/ValidationBouteilleSaq.jsx, API-vino/react/src/composants/Validation/ValidationInscription.jsx, API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/Formulaire/AjoutBouteille.jsx, API-vino/react/src/vues/Inscription/Inscription.jsx, API-vino/react/src/vues/Login/Login.css, data/vino_sql
=> Validation du formulaire ajoute bouteille de la SAQ

API-vino/app/Http/Controllers/UsagerController.php, API-vino/composer.lock, API-vino/react/src/App.jsx, API-vino/react/src/composants/Validation/ValidationModifier.jsx, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/ModifieUsager/ModifieUsager.css, API-vino/react/src/vues/ModifieUsager/ModifieUsager.jsx, API-vino/routes/api.php
#14 
créer la modification de la page et effectuer la validation
=> Modifier l'utilisateur 

API-vino/app/Http/Controllers/UsagerController.php, API-vino/react/src/App.jsx, API-vino/react/src/composants/UI/Modal/ModalInscription.jsx, API-vino/react/src/composants/Validation/ValidationAjouterUsager.jsx, API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/AjouteUsager/AjouteUsager.css, API-vino/react/src/vues/AjouteUsager/AjouteUsager.jsx, API-vino/react/src/vues/ModifieUsager/ModifieUsager.jsx, API-vino/routes/api.php
=> ajoute usager dans espace admin

API-vino/app/Http/Controllers/BouteilleController.php, API-vino/app/Http/Controllers/CellierBouteillesController.php, API-vino/app/Http/Controllers/CellierController.php, API-vino/react/src/App.jsx, API-vino/react/src/assets/css/modales.css, API-vino/react/src/composants/Bouteille/Bouteille.jsx, API-vino/react/src/composants/ImportationSAQ/ImportationSAQ.jsx, API-vino/react/src/composants/Validation/ValidationBouteille.jsx, API-vino/react/src/composants/Validation/ValidationBouteilleSaq.jsx, API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/Admin/AdminStatistique.jsx, API-vino/react/src/vues/Formulaire/AjoutBouteille.jsx, API-vino/react/src/vues/Formulaire/ModifieBouteilleSAQ.jsx, API-vino/routes/api.php
issue #21 Statistique 
issue #22 Modification D'une bouteille dans le catalogue
=> Ajout de la page statistique

API-vino/react/src/vues/Admin/Admin.css, API-vino/react/src/vues/Admin/Admin.jsx, API-vino/react/src/vues/AjouteUsager/AjouteUsager.css, API-vino/react/src/vues/AjouteUsager/AjouteUsager.jsx
=> supprimer le bouton et ajouter l'icône , gestion usager 

API-vino/react/src/vues/AjouteUsager/AjouteUsager.jsx, API-vino/react/src/vues/CompteUsager/CompteUsager.jsx, API-vino/react/src/vues/CompteUsager/ModifieCompte.jsx, API-vino/react/src/vues/ModifieUsager/ModifierUsager.jsx
=> ajoute modal success pour modifier,ajouter,supprimer
